server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;

        # Allow other MFEs to fetch the remoteEntry.js and chunks
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;
    }

    # Ensure JavaScript modules have the correct MIME type
    types {
        application/javascript js;
        text/html html;
        text/css css;
    }
}